
describe('empty spec', () => {
  it('data received from api', () => {
    cy.visit('http://localhost:4200')
    cy.contains("convert to")
    cy.contains("calcul of")
    cy.contains("rectangle")
    cy.contains("circle")
    cy.contains("triangle")
    cy.contains("square")
  })
  it('test select perimeter', () => {
    cy.get('#need').select('perimeter').should('have.value','perimeter')
    cy.get('.result').contains('perimeter')
    cy.contains('m')
    cy.get('.convert').contains('km')
    cy.get('.convert').contains('m')
    cy.get('.convert').contains('dm')
    cy.get('.convert').contains('cm')
    // cy.get('#figure').select('rectangle')
    // cy.get('#longueur').type('15').should('have.value', 15)
    // cy.get('#largeur').type('5').should('have.value', 5)
    // cy.contains("calcul of").click()
    // cy.get('#result').should('have.value', 40)
  })
  it('test select area', () => {
    cy.get('#need').select('area').should('have.value','area')
    cy.get('.result').contains('area')
    cy.contains('m²')
    cy.get('.convert').contains('km²')
    cy.get('.convert').contains('m²')
    cy.get('.convert').contains('dm²')
    cy.get('.convert').contains('cm²')
  })
  it('fugure is rectangle', () => {
    cy.get('#figure').select('rectangle').should('have.value','rectangle')
    cy.contains('longueur')
    cy.contains('largeur')
  })
  it('fugure is square', () => {
    cy.get('#figure').select('square').should('have.value','square')
    cy.contains('side')
  })
  it('fugure is circle', () => {
    cy.get('#figure').select('circle').should('have.value','circle')
    cy.contains('circle')
  })
  it('fugure is triangle', () => {
    cy.get('#figure').select('triangle').should('have.value','triangle')
    cy.get('#need').select('area').should('have.value','area')
    cy.contains('base')
    cy.contains('height')
    cy.get('#need').select('perimeter').should('have.value','perimeter')
    cy.contains('side1')
    cy.contains('side2')
    cy.contains('side3')
  })
})
